### ISSUE TITLE
linkLayer - error 'Cannot read properties of undefined (reading 'source')'}

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2-lib#1024]
with lib 1.10+ in IGO2- assembling, when you enter context 'synchronisation de layer' 
an error is throw:
'Cannot read properties of undefined (reading 'source')'

![image](https://user-images.githubusercontent.com/32003632/160453936-02c863fc-38b6-4ed2-a962-8131b07f2b53.png)

* **Igo Version:**
1.10

**Comment by pelord** [comment]
fixed in the next release.
