### ISSUE TITLE
ol.geom.Cricle not supported

### ISSUE THREAD

**Issue by BelangerD** [infra-geo-ouverte/igo2-lib#107]
https://github.com/infra-geo-ouverte/igo2-lib/blob/911103f043a72d45d57fa9f71bc3529a01eedcbb/src/lib/feature/shared/feature.interface.ts#L22

The property "type" of the interface FeatureGeometry is defined as ol.geom.GeometryType, but the geometry type "Circle" cause an error when is is added to the overlay.

Altering the properties of the feature owning the geometry do not change the issue. Adding properties "center" and "radius" defined in ol.geom.circle. it did not change the issue

Tested with release 0.13

**Comment by mikesmichael** [comment]
You are right. Circle doesn't exist in a GeoJSON. We fix the type list in pull request #144. If you need to create a circle with geoJSON we suggest to use a point with a style that correspond to the radius of the circle. See [example](https://github.com/geo-msp/apercu-qc/blob/0861190ae1ef614200f11f1958dffd71b8a06644/contexts/embacle.json#L85)
