### ISSUE TITLE
How to install igo2-lib ver 1.11.1 ?

### ISSUE THREAD

**Issue by AkshayGore** [infra-geo-ouverte/igo2-lib#1076]
**Please tell us about your environment:**

* **Igo Version: 1.11.1**

* **Node:**

How to run igo2-lib ver 1.11.1 in windows?
Which node/npm version required?

Error:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1202.9',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v14.17.3', npm: '8.10.0' }
npm WARN EBADENGINE }

**Comment by pelord** [comment]
here. I'm running these versions...
![image](https://user-images.githubusercontent.com/7397743/175384427-1383129b-bf5f-4ff3-a44c-f425555ef29c.png)

**Comment by pelord** [comment]
I'll try to update to npm 8 and give you some feedback!

**Comment by pelord** [comment]
The current version of igo2-lib is based on angular 12.

Angular 12 require  npm: '^6.11.0 || ^7.5.6'

I have tried with Node : 'v16.15.1' and npm: '8.11.0'. Here the warn i've got:
![image](https://user-images.githubusercontent.com/7397743/175452148-da22e48a-3e8d-4aa9-be40-476424fdc2b6.png)


Try to downgrade to npm ^6.11.0 || ^7.5.6 
OR
This summer, we will update the lib to Angular 14. This might resolve your issue.

**Comment by pelord** [comment]
for info. I use nvm-window to toggle between my node versions. 

![image](https://user-images.githubusercontent.com/7397743/175452684-dd80ae9d-5a29-415e-a18c-0b01dccb6108.png)

**Comment by AkshayGore** [comment]
Thanks So much
Its help me lot.
Can you please guide me how to set up igo2-api /ldap with this?

**Comment by pelord** [comment]
I will review the igo2-api this summer with the ldap component.

**Comment by AkshayGore** [comment]
how to add single component in Angular 12 and node 14.17.1 demo app?
For ex. I have created a demo app in Angular 12 and node 14.17.1 environment. what are the steps/or commands library need to be install to run igo2 geo components?

**Comment by AkshayGore** [comment]
> I will update the igo2-api this summer with the ldap component.

Thanks so much. 
If you upgrade igo2 lib for angular 14 and above its help lots for everyone.
Igo2 is very good tool. Only thing is it required documentation/YouTube video of installation and configuration.

**Comment by AkshayGore** [comment]
> how to add single component in Angular 12 and node 14.17.1 demo app? For ex. I have created a demo app in Angular 12 and node 14.17.1 environment. what are the steps/or commands library need to be install to run igo2 geo components?

I am trying to add measure component in my demo app.
https://github.com/infra-geo-ouverte/igo2-lib/tree/master/demo/src/app/geo/measure

**Comment by pelord** [comment]
@AkshayGore Sorry for delayed answer.. do you still need some support?
