### ISSUE TITLE
Issue when removing layers

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#1088]
* **Igo Version:**
1.12.1

There is an issue when removing layers that sometimes cause the web browser to crash or, in the better case, requires up to a few minutes of waiting. This is a huge issue when changing context and the `igoLayerContext` directive has `removeLayersOnContextChange` set to false.

The culprit is the `removeLayers` method of `map.ts` as shown here.
https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/map/shared/map.ts#L317

It's quite difficult to understand what the method attempts to do (remove linked layers?) but it does a lot of nested iterations over list of layers and, mostly, at line 333 it pushes items in a list currently being iterated over.

The method should be optimized to avoid recursivity issues.

**Comment by pelord** [comment]
@cbourget The method has been refactored during 1.13.x migration. Could you validate if this issue is still present on 1.13.4 or + ?
