### ISSUE TITLE
The color picker position is not correct in latest upgrade v14

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1330]
https://github.com/zefoy/ngx-color-picker/issues/331

We also have some style adjustment to do in the StyleModalDrawing when we click on the color picker we have some absolute position apply on the input, who cause a layout shift

**Comment by LAMM26** [comment]
La position semble être ok. Par contre avec le nouveau color picker il n'est pas possible de gérer le canal alpha pour la transparence?

**Comment by LAMM26** [comment]
La transparence est maintenant ajustable
