### ISSUE TITLE
Contexts: keep the same circles radius for imported draw layers

### ISSUE THREAD

**Issue by aziz-access** [infra-geo-ouverte/igo2-lib#1358]
Now, if we import a draw layer containing circles, the radius of the circle changes, 
we must keep the same circles radius if we import a draw layer.

**Comment by LAMM26** [comment]
La couche/dessin semble être ajouté, mais invisible à l'écran. (un cercle a été dessiné, exporté en geojson puis réimporté)
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/83651899/7d5ecb98-9531-4751-9c03-578f9fb8bcbf)
