### ISSUE TITLE
TimeFilter style regression 

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1360]
After the Angular v15 migration, we found many style regressions in the TimeFilter tab. This section is complex to test and requires specific configuration to see all the details.

One example among many others:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/f4a5143e-3c1f-485c-8f43-2ba16d98dcbb)

**Comment by LAMM26** [comment]
Testé sur 16.0.0-rc.1, sur plusieurs couches. Semble être ok
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/83651899/888cfeb1-a437-4dde-bb40-b97300020202)
