### ISSUE TITLE
Various regression related to version 16.x (next branch)

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#1361]
* **Igo Version:**
next branch (16.x)

- [x] 1-Overall, the placement of the toggle buttons.. they are now on the left. --> Fixed by https://github.com/infra-geo-ouverte/igo2-lib/commit/c87cb1faae444fa015f7176c81dc42221384c073
- [x] 2-Global placement of measurement results inside the table
- [x] 3-Place overflow direction text on 2 lines rather than hidden. ==> Fixed by https://github.com/infra-geo-ouverte/igo2-lib/commit/a3b09a47dd9061d23af3071cb44fcad4b1dcfc8d
- [x] 4-warnings on mat-badge (ex in catalog) Detected a matBadge on an "aria-hidden" "<mat-icon>". Consider setting aria-hidden="false" in order to surface the information assistive technology. Refer to https://github.com/angular/components/issues/27035 ==> Fixed by https://github.com/infra-geo-ouverte/igo2-lib/commit/426204e8b628a0c117d6e9d25c31ae6f7904b43c
- [x] 5-disposition in confirmation dialog (data import), ==> No fix needed. The dialog is identical as As Angular material design.  
- [x] 6-Overall, is the typography respected?
- [x] 7- Color of query results icons and layer title. ==> Kept as is.
- [x] 8- workspace are not selectable  ==> Not a real error. Probably caused by a developper issue due to cross site dev on 
localhost and localstorage conflict ... (shame)
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/7397743/59a05679-d4e3-41de-abec-635c9826ba2d)
- [x]  9- Workspace paginator was not positioned on right side ov the view port. ==> Fixed by https://github.com/infra-geo-ouverte/igo2/commit/3c2881b4249f0570424721451e433dbbeb3bc318
- [x] #1406
- [x] 11- Cannot read properties of undefined (reading 'visible') ==> Fixed by https://github.com/infra-geo-ouverte/igo2-lib/commit/87239f6b11cba16b97bea354482645e05edd9ef6
- [x] 12- main.ts:14 Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide ==> Normal. It is due to the fact that the style is provided with a delay within the APP_INITIALIZER. 
- [ ] 13- Actions aligmement in workspaces

**Comment by pelord** [comment]
Checked regressions are fixed.

**Comment by alecarn** [comment]
1- Les icones du résultat de la recherche sont grisé
<img width="540" alt="image" src="https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/37d3022d-b505-4696-9652-318aad52b641">
2- La barre de recherche principale de l'application ne devrait pas avoir de fond grisé
3- Le champ pour filtrer les couches aussi ne devrait pas avoir le fond grisé.
