### ISSUE TITLE
The HomeExtent button doesn't seem to work

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1391]
In the IGO2-LIB demo, we have the HomeExtent button in many pages and I don't find a page where the button work. You can test on the Simple Map or Context page.

**Comment by aziz-access** [comment]
the bug here is about the default value of `extentOverride` and the config `homeExtentButton` both are `undefined`.

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/86438702-64b5-4292-ba7f-37be724803fb)
