### ISSUE TITLE
ogc-filter multiple outputFormatDownload support

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2-lib#147]
In the ogc-filter tool, it is not possible to include more than one outputFormatDownload value. It can be useful depending on the case to  have more than one download format supported, such as SHP, GML, CSV, GeoJSON, KML...

**Comment by pelord** [comment]
Enhancement?

**Comment by matrottier** [comment]
should this option not be related to the import / export tool ?
