### ISSUE TITLE
Visibilité des couches vs hors plage de résolution

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#1492]
* **Igo Version:**
16.x +

Voici les couleurs que les couches devraient avoir selon leur statut.
noir => non visible
gris => non disponible selon la plage de resolution définies
bleu (ou vert), couleur principale du theme => visible

Actuellement, le statut noir n'est pas respecté. 

![chrome_2023-11-09_13-53-16](https://github.com/infra-geo-ouverte/igo2-lib/assets/7397743/c785fbac-983f-4014-973d-e858f1f7b86a)

**Comment by pelord** [comment]
related to https://github.com/infra-geo-ouverte/igo2-lib/commit/9221c04ba49f678ea222e2ff68ee7f748e0d863d

**Comment by alecarn** [comment]
Des changements ont été apporté globalement au thème. Nous avons enlevé les modifications au foreground ce qui pourrait impliquer des changements mineur de couleurs a certains endroits.

**Comment by MSPKarengeo** [comment]
I have carried out some tests with some layers where the colors required according to the state of the layer are correct. So I would say that this task is done.
