### ISSUE TITLE
chiffres de la liste de l'outil de mesure ne suivent pas le changement d'unités

### ISSUE THREAD

**Issue by aziz-access** [infra-geo-ouverte/igo2-lib#1499]
lorsqu'on change les unités dans l'outils de mesure, les chiffres msesurés de la liste à cocher ne changent pas, ils restent dans l'unité dans laquelle ils ont été mesurés au départ.
idem pour superficie

![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/91bcb875-703e-470d-8488-2fdfee691e97)

**Comment by MSPKarengeo** [comment]
Les changements d'unités de mesure s'effectuent sans problème sur la carte, mais les valeurs ne sont pas mises à jour dans le tableau détaille. Lorsqu'une valeur est sélectionnée dans le tableau des détails, elle est modifiée dans l'unité de mesure sélectionnée ultérieurement (c'est-à-dire que la modification est effectuée à la fin et pas avant).
Je pense qu'il serait bien d'avoir, par exemple : 1) une ou plusieurs valeurs sélectionnées et de faire changer l'unité, dans ce cas le tableau de détails et la carte devraient changer en même temps. 2)Toutes les valeurs sélectionnées doivent changer d'unité à la fois sur la carte et dans le tableau des détails.


![Image](https://github.com/infra-geo-ouverte/igo2-lib/assets/90481471/4a393b2e-b5ab-4c77-8650-b6b3da89a21c)

**Comment by MSPKarengeo** [comment]
Le changement d'unité de chacune des mesures fonctionne correctement, qu'elle soit linéaire ou polygonale, elle est modifiée correctement. Le seul détail que j'ai identifié est que lorsque nous sélectionnons certaines mesures et que nous devons changer l'unité de ces mesures, par défaut, l'outil change les unités de ces mesures sélectionnées et les autres également. Je ne vois pas de gros problème de ce côté-là, c'est-à-dire que cela ne nuit pas à l'expérience utilisateur.
