### ISSUE TITLE
Error when npm run build.prod for newest master version

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2-lib#150]
ERROR in node_modules/@igo2/igo2/dist/lib/layer/layer-item/layer-item.component.html(99,7): : Property 'dynamicUrl' does not exist on type 'DownloadOptions'.

It should be validate, why the error above happens? this option is private ?: 

This works, but not the best options : 
*ngIf="layer.dataSource.options.download && (layer.dataSource.options.download['dynamicUrl'] || layer.dataSource.options.download['url'])"

**Comment by pelord** [comment]
temporary solved in PR #160
