### ISSUE TITLE
boutons +- disparaissent et affichage mode mobile Outils avancés

### ISSUE THREAD

**Issue by aziz-access** [infra-geo-ouverte/igo2-lib#1500]
en réduisant la taille de la fenêtre du navigateur en horizontal, les boutons de zoom + - disparaissent (lorsque la fenètre est entre un tiers et moitié de l'Écran).
1- largeur 1280px tout va bien:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/5d012bd8-d300-42f4-baa1-68c0816e5f66)

2- largeur 1279px boutons + - disparaissent:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/f227cdc0-b415-4124-b633-c46cf56930ba)

mode mobile Outils avancés:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/4b98d0c1-3c3b-41dc-83d7-f5b495a8865e)

**Comment by aziz-access** [comment]
mode mobile Outils avancés:
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/119948730/4b98d0c1-3c3b-41dc-83d7-f5b495a8865e)

**Comment by alecarn** [comment]
Il y a eu une refonte dans la gestion du positionnement des boutons d'actions de la carte. Il serait important de tester avec touts les panneaux qui pourrait influencer le positionnement des boutons.

**Comment by MSPKarengeo** [comment]
I have carried out the test and the buttons disappear when the size is less than 599px.


![Image](https://github.com/infra-geo-ouverte/igo2-lib/assets/90481471/1bfacfae-ab12-4824-a0c7-c0994e17fd19)

**Comment by MSPKarengeo** [comment]
The following models have the same problem:
Samsung Galaxy A51/71 412px, iPhone SE 375px, iPhone XR 414px,
Galaxy fold 280px, Iphone12 Pro, Iphone 14 ProMax 430px, Pixel 7 412px, Samsung Galaxy S8 360px, Samsung Galaxy S20 Ultra 412px. The new cell phone formats: Surface duo with 540px, are also not recognized.

**Comment by alecarn** [comment]
This is a wanted behavior, the zoom buttons should not appear on touch screen or on a screen less than 599px.

**Comment by alecarn** [comment]
Après discussion avec Karen le ticket semble conforme
