### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#1508]
**Please tell us about your environment:**

* **Igo Version:**
16.x +

The color picker, related to an imported layer, the color change is impossible.

Prior to 16.x, the color picker was outputing values on change. Then, the layer color was change.

Due to the refactor to the color picker, there is no emitted color, then the layer color is not changed.

**Comment by MSPKarengeo** [comment]
When I try to modify a geojson file, in this case a point, the utility has an error and does not recognize the colors nor does it select them. The figure below shows it clearly. 


![Image](https://github.com/infra-geo-ouverte/igo2-lib/assets/90481471/5ae33994-dfc2-4f69-b1c6-e82ae9ed5696)

**Comment by MSPKarengeo** [comment]
I have carried out different tests in geojson, kml and gml formats. Everything is modified correctly when changes are made to the layers
