### ISSUE TITLE
Baselayer Switcher stay open without useStaticIcon

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1534]
If we have two basemaps and we don't set the `useStaticIcon` the switcher stay open. 
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/34d611e3-999f-4e84-b87a-2bdf46babf94)

**Comment by aziz-access** [comment]
@alecarn  j'ai besoin de plus d'informations sur l'utilité de ce paramètre

**Comment by alecarn** [comment]
For useStaticIcon we can have an icon button or if false we show the first igo-mini-basemap. Test it to see the difference!
