### ISSUE TITLE
Search-bar style regression

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2-lib#1541]
In the latest upgrade for the v16 we made some style changes for search-bar to accommodate the search bar in IGO2. On the other hand this caused regressions, when used as a FormField the density is smaller and we override other style like the Subscript, background-color and other styles. The modifications should be moved locally to the IGO2 application instead of impacting the library. In this screenshot changes has been made to fix some style regression
```
:host {
  igo-search-bar ::ng-deep {
    .mat-mdc-form-field-subscript-wrapper, .mdc-line-ripple {
      display: initial;
    }

    .mat-mdc-text-field-wrapper,
    .mat-mdc-form-field-focus-overlay {
      background-color: var(--mdc-filled-text-field-container-color) !important;
    }
  }
}
```
![image](https://github.com/infra-geo-ouverte/igo2-lib/assets/133774929/f088bd79-c93f-45ee-a47c-47f085812a77)

**Comment by aziz-access** [comment]
Another style regression with input label.
`<igo-search-bar [label]="'test'"></igo-search-bar>`
The label is hidden
