### ISSUE TITLE
Drag box is not recognized 

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#161]
https://github.com/infra-geo-ouverte/igo2-lib/blob/2cd2bfaa1b65a922a1b0bf8a322071b1ff910dc0/src/lib/query/shared/query.directive.ts#L68

This interaction do not work with a build version of IGO2 https://github.com/infra-geo-ouverte/igo2 

This interaction works properly into 
igo2-lib  npm start  & igo2 npm start 

The dragBox  in igo2 npm "start.prod" do not work at all. 

Various solutions:
- Fix the dragBox problem in the built version
- or
- Replace by drawing a polygon. This option will also support mobile versions.

**Comment by mbarbeau** [comment]
fix in 0.22.0
