### ISSUE TITLE
Print crossOrigin layers

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo2-lib#182]
Add a validation when crossOrigin layers are added.

Try to use them with "crossOrigin: anonymous".
If it's failing, tell user if he want to add the layer without the crossOrigin, that will tainted the map and break the print. Print will be available only after browser refresh.

**Comment by pelord** [comment]
@mbarbeau  is it fixed?

**Comment by mbarbeau** [comment]
The request is to add a message to the user. Close since we just have to add the layers correctly.
