### ISSUE TITLE
Layers list empty space

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#187]
**Please tell us about your environment:**

Windows 7, Chrome 69.0.3497.92

* **Igo Version:**
latest

* **Node:**

10.9.0

In the layer list, there is an empty space at the top. I think this is related to the layer filters being unavailables when there is less than 5 layers.
![igo2-layer-filter-blank-space](https://user-images.githubusercontent.com/2046987/46105177-584be900-c1a3-11e8-811e-3e527bda4a92.jpg)

IMO, we should be able to decide in the context if we want filters or not. Optionnaly, it could be interesting to make the number of layers threshold configurable too.

In any case, when thre are not filters, there shouldn't be an empty space at the top.

**Comment by cbourget** [comment]
Yes, I agree. Will do.

**Comment by pelord** [comment]
Closed by #190
