### ISSUE TITLE
Form layout

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#188]
**Please tell us about your environment:**

Windows 7, Chrome 69.0.3497.92

* **Igo Version:**
latest

* **Node:**

10.9.0

I feel like there are some issues with the forms in their current state. Those are my opinions and feel free to disagree with them. 

Take the print form for example:

![igo2-form-layout](https://user-images.githubusercontent.com/2046987/46105609-7b2acd00-c1a4-11e8-823f-8cd9ac9e2412.jpg)

1. On the left and right the fields are too close to the edge.

- There should be some kind of padding

2. The print button bottom shadow is not visible.

- Again, the form should have some padding and the button(s) could benefit from a margin

3. Text fields have a bottom margin but checkboxes and radiobuttons don't which make the form too compact.

- Checkboxes should be grouped and have a bottom margin
- Radio groups should also have a bottom margin

4. The print button placement seems odd. This might be applicable only in the sidenav context.

- Form buttons could be centered or right aligned.

Open for discussion

**Comment by mbarbeau** [comment]
I added some padding around the form and moved the button to the center.

**Comment by mbarbeau** [comment]
Yes for the 2nd point.
About point 3, checkboxes have a bottom margin but I have not grouped them.

**Comment by cbourget** [comment]
Alright. I think we should handle point 3 because while the space between checkboxes is acceptable, the last checkbox is too close to the next form field.
