### ISSUE TITLE
NotificationType build error

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#194]
**Please tell us about your environment:**

* **Igo Version:**
0.23.1

* **Node:**
10.9.0

In the message service, the message type is casted as string and that causes a build error. It should be casted as angular2-notifications.NotificationType instead.

**Comment by pelord** [comment]
@cbourget  - Does this commit fix the issue?
https://github.com/infra-geo-ouverte/igo2-lib/commit/6e09cb2e1b0778bfb7ad718eed957b07b947e83b
