### ISSUE TITLE
problem with get info on mobile device

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2-lib#197]
20181005 version in production on Donnée Québec : https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/
 
When you are on mobile device, when you click on a item (point, polygone) in a layer (getfeatureinfo), the info of the item doesn't display... 

To show you have to go to the search menu and clic on tge result and to can see the information at the bottom of the map window.

Exemple: Here a point is select and no info is display
https://chat.msp.gouv.qc.ca/file-upload/2cTGNhRi8mYELxRPF/Clipboard%20-%205%20octobre%202018%2012:18

**Comment by gignacnic** [comment]
@pelord have you got time, to check this item?

**Comment by pelord** [comment]
Seem to be solved with the new lib.

**Comment by cbourget** [comment]
Closing as it appears to be fixed. Reopen if it's still an issue.
