### ISSUE TITLE
Query Directive forkjoin deprecated

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#229]
**Please tell us about your environment:**
Window 7 when running ng test & ng lint on geo component
* **Igo Version:**
0.24.2

* **Node:**
Node 8.11.3
Angular: 6.1.10

When running ng lint on geo component, here my warnings:

WARNING: .../igo2-lib/projects/geo/src/lib/query/shared/query.directive.ts[190, 11]: forkJoin is deprecated: resultSelector is deprecated, pipe to map instead

Various way to fix this issue:

1. pipe to map instead
2. Validate if the condition where the forkjoin stand is still usefull. I think this part is unused. All code related to waitForAllQueries could/should be removed. @cbourget Do you agree?
`      if (this.waitForAllQueries) {
        this.queries$$.push(
          forkJoin(...queries$).subscribe((features: Feature[][]) =>
            this.query.emit({
              features: features
                .filter(f => f.length > 0)
                .concat(parsedClickedFeatures),
              event: event
            })
          )
        );
      }`

**Comment by cbourget** [comment]
I agree with you that if this code is not used, we should remove it. If we keep it, I think replacing forkJoin with zip would work withtout changing anything else.

**Comment by pelord** [comment]
:+1:

**Comment by mbarbeau** [comment]
I think the code is useful. It's used in geoinondation to combine queries into one.

**Comment by pelord** [comment]
I've tried to set waitForAllQueries to true. Nothing seem to be triggered (with forkjoin OR zip). 
@mbarbeau Can you check it?

**Comment by pelord** [comment]
Have been moved into a zip..

https://github.com/infra-geo-ouverte/igo2-lib/blob/824ba25c0c0c57de5a9899c0b8ae8ddce796970b/packages/geo/src/lib/query/shared/query.directive.ts#L162
