### ISSUE TITLE
Sharing URL and visible layers

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#237]
When sharing an URL like :

[https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=mtq&zoom=7&center=-72,47.99999999999997&invisiblelayers=*&visiblelayers=aeroport,9ae01ef70a10a11b584a9aae295ed925& ](https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=mtq&zoom=7&center=-72,47.99999999999997&invisiblelayers=*&visiblelayers=aeroport,9ae01ef70a10a11b584a9aae295ed925&)

You have a list of visible layers. in this case, my visible layers are 1 base layer and a layer named aeroport.

I propose when sharing URL formatted this way, only visible layers should be shown into the TOC (table of content). Here an image for my proposal.

![image](https://user-images.githubusercontent.com/7397743/48733692-65b8a900-ec11-11e8-9426-78825ce40e42.png)

Waiting for comments!

**Comment by cbourget** [comment]
The current behavior is to show the invisible layers in the layer list with the display button set to hidden (closed eye) right?

A user would have to turn off the filters to see those layers in the layer list is that right?

If so, then we'd have to make sure the filter tool is always present, even when the number of layers is below the minimum threshold (see #191 ).

**Comment by pelord** [comment]
Yes. 
1. The current behavior is to hide/display layer from map. 
2. Yes the user would have to turn off filter.
3. You are right again. In this case, if number of layer is inferior to the threshold, nothing should triggered. Simply show the layer list.

**Comment by cbourget** [comment]
Thanks. I haven't used this feature myself but I think what you propose makes sense.

**Comment by pelord** [comment]
I think this might be particularly useful for large thematic/view/context containing many layers.

**Comment by pelord** [comment]
I think the prior proposal would be annoying for some user. If we filter shown layers based on visibleslayers params, only some will appreciate the default behavior of the layer list.

Here a new proposal, based on new url parameters.
adding : 
- lck=filteringkeyword
- lca=1 or 0 (Boolean for alpha sorting)
- lcv = 1 or 0 (Boolean to show only visible)
- lcr = 1 or 0 (Boolean to show only layers in range)

I could also add these properties the every publish context.json to control the layer list appearance on init.  

Waiting for comments! :)

**Comment by tqgeomatique** [comment]
If we can control the behavior of the filter when sharing URL, as you told, it looks fine to me.

**Comment by pelord** [comment]
Resolved by PR #248
