### ISSUE TITLE
Time filter not active for layers added from catalog

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2-lib#240]
When a time filterable layer is added to the map from the catalog, the time filter is not enabled.

**Comment by ameliebernier** [comment]
The cause seems to be that the timeFilterable layer options is not set to true from the GetCapabilities.

**Comment by pelord** [comment]
This one is now fixed? @ameliebernier ?

**Comment by ameliebernier** [comment]
Fixed
