### ISSUE TITLE
Time filter with "optionsFromCapabilities: true" is always set to type 'date'

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2-lib#242]
When time filter is not defined in context but obtained from service capabilities, the time filter type is not set and then defaults to type 'date'. 

As a result services like this one (updated every 6 hours) are not queried appropriately because the hours are truncated:

https://testgeoegl.msp.gouv.qc.ca/apis/ws/geomet?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities&layers=HRDPA.6F_PR

**Comment by ameliebernier** [comment]
The proposed fix would be to infer the type of filter ('date', 'time', 'dateTime' or 'year') from the date format in the dimension tag

**Comment by pelord** [comment]
Yes. For sure. WMS dimension are already read by could be improved in:

https://github.com/infra-geo-ouverte/igo2-lib/blob/62404264dc1f7dab2f7d00557af9ae0eb0de7f94/projects/geo/src/lib/datasource/shared/capabilities.service.ts#L286

**Comment by ameliebernier** [comment]
Also I think there should be some check for dimension name (should be 'time')

**Comment by pelord** [comment]
Maybe the solution is to let the user control which type of time filter he want to have?

**Comment by ameliebernier** [comment]
Yes maybe 

Will the different filters work with every possibilities? Like the example above, if the user sets it to use only dates the query will not resolve correctly and nothing will be returned
