### ISSUE TITLE
Why do I need to build the library everytime I make changes?

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#243]
xD**Please tell us about your environment:**

* **Igo Version:**
0.24.2
* **Node:**
v8.11.3
"@angular/cli": "~6.0.1",
"@angular/compiler-cli": "^6.0.0",

Why do I need to build the library everytime I make changes?

About this issue:
https://github.com/angular/angular-cli/wiki/stories-create-library#why-do-i-need-to-build-the-library-everytime-i-make-changes

This should be fix with Angular-cli 6.2.x . At this moment, the project use angular-cli 6.0.1. Need to update dependencies before.

Need to update angular-cli to fix it.

**Comment by pelord** [comment]
I've tried many ways. At this moment the simpliest way is to run :

1. shell to build a part of the library and the 
2. another shell to run the app

ex:

**1st shell: npm run build.geo --watch**
_... another shell for each part of the lib you want to watch._ 
**2nd shell npm start**

**Comment by pelord** [comment]
Here what i've tried.

- https://github.com/angular/angular-cli/issues/10643
- https://mereommig.dk/en/blog/adding-livereload-to-the-angular-cli-libraries
- https://igormilla.com/post/serving-local-libraries-during-development-of-angular-application

**Comment by mbarbeau** [comment]
To try: npm run start.watch

**Comment by pelord** [comment]
👍  works perfectly.
