### ISSUE TITLE
angular 7 upgrade

### ISSUE THREAD

**Issue by chinnarao** [infra-geo-ouverte/igo2-lib#255]
Please upgrade angular 7 , if not can you tell me the reasons or road map?
![image](https://user-images.githubusercontent.com/3664053/50542256-0c2b8e80-0b6e-11e9-93fc-2e48aa6eae5d.png)

Please update angular notification latest release 
https://github.com/flauc/angular2-notifications.

**Please tell us about your environment:**

windows 10 , chrome latest

* **Igo Version:**
2.0 (IGO-2) / Open GIS Infrastructure 2.0 Library
* **Node:**

11.0

**Comment by cbourget** [comment]
Hello,

@mbarbeau could give you a definitive answer when he'll get back from vacations but I'm pretty sure the project will upgrade to angular 7.

The same goes for angular2-notifications.

I guess it'll be done soon but, again, this is not a definitive answer.

Thank you,

**Comment by sukeshlaghate** [comment]
any updates on support for Angular 7?

**Comment by mbarbeau** [comment]
The migration to Angular 7 is planned and will be done within a few weeks.

**Comment by mbarbeau** [comment]
Available in version 1.0.0-alpha.1
The branch will soon be merged into master
