### ISSUE TITLE
Print comment misplaced

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#280]
**Please tell us about your environment:**

* **Igo Version:**

* **Node:**

When printing a map with a comment, the comment is misplaced and only partially misplaced. See that screenshot.

I can try and fix this but there is a lot going on in the print service so any clue is welcome.

![print_comment](https://user-images.githubusercontent.com/2046987/55161298-9074ba00-513b-11e9-810d-667e2d4dfe20.jpg)

**Comment by mbarbeau** [comment]
You can have a look here: https://github.com/infra-geo-cover/igo2-lib/blob/fc905d4db2e51c7134c120c720d7a1fa1aaa70c90/projects/geo/src/lib/print/shared/print.service.html L190

**Comment by mbarbeau** [comment]
The bug was only present in version 1.0.0-alpha.1
Fixed by this commit 45d28834e959f3d59c8ccb91c9b1a9f0965b9277
