### ISSUE TITLE
Search by coordinates - iCherche

### ISSUE THREAD

**Issue by Fr3d3rik777** [infra-geo-ouverte/igo2-lib#288]
**Please tell us about your environment:**

Windows 7, Chrome 73
* **Igo Version:**
1.0.0-alpha

The coordinates must currently be entered backwards from what is done in Google Maps.
The GMaps way is  46.742221,-71.257608.
The actual IGO2-lib way is -71.257608,46.742221.

With GLO, it was possible to enter the coordinates of two different ways (Ex.: 46.742221,-71.257608 or -71.257608,46.742221) and it's always point at a place in Québec. I guess it was managed in the code to presume that we were here (If a value is between 40 and 50, it's considered a lattitude and the other like a longitude).
Is it possible to get the same behavior as GLO or to follow the standard established in GMaps?

**Comment by mbarbeau** [comment]
This is not a bug of IGO, but a feature to add in iCherche.

**Comment by cbourget** [comment]
Is there any plan to add it to iCherche?

**Comment by cbourget** [comment]
@mbarbeau
