### ISSUE TITLE
Print enhancements

### ISSUE THREAD

**Issue by Fr3d3rik777** [infra-geo-ouverte/igo2-lib#289]
**Please tell us about your environment:**

Windows 7, Chrome 73
* **Igo Version:**
1.0.0-alpha

- The slides toggle should be on the right of the text like the measuring tool.
- When selecting the output format "Image", new slide toggle "Compress files", we would replace it with "Compress file" considering that there is only one file to compress. In french "Compresser le fichier".
- Also when selecting the output format "Image", the "Imprimer" button is replaced by "Sauvegarder", there should only be one button, since the tool does not really allow to print but only to save a file in Pdf format or in image format (of different formats). The current wording is "Sauvergarder", it must be corrected by "Sauvegarder".
- Adjust the wording "Lettre" and "Légal" in the list of paper sizes. Translate in french the current ones.
- Alphabetical order the elements of the differents lists.
- The bottom comment is hidden when you do not display the legend, projection, and scale but i think it's included in the #280 issue.

**Comment by mbarbeau** [comment]
- The slides toggle should have another color when activated.

> The bottom comment is hidden when you do not display the legend, projection, and scale but i think it's included in the #280 issue.

Yes, it's fixed by #280

**Comment by cbourget** [comment]
I guess we can move forward with those?

**Comment by cbourget** [comment]
This is done.
