### ISSUE TITLE
Import enhancement

### ISSUE THREAD

**Issue by Fr3d3rik777** [infra-geo-ouverte/igo2-lib#290]
**Please tell us about your environment:**

Windows 7, Chrome 73
* **Igo Version:**
1.0.0-alpha

- Replace "Projection de l'intrant (EPSG:4326)" by the text "Système de coordonnées" above the input field and put the EPSG:4326 enterable field below and only 4326 would be editable.
- When importing a file, a zoom should be made on the elements and make them more visible.
- Add support for GML files

**Comment by cbourget** [comment]
Done
