### ISSUE TITLE
Export enhancements

### ISSUE THREAD

**Issue by Fr3d3rik777** [infra-geo-ouverte/igo2-lib#291]
**Please tell us about your environment:**

Windows 7, Chrome 73
* **Igo Version:**
1.0.0-alpha
- Adjust the wording of the "Données géospatiales" drop-down list instead of "Couche".
- Adjust the wording of the "shapefile" item for "Shapefile" in the list of export formats and put in alphabetical order.
- Validation to add when the export has no item and display the message "You must select at least one item before you can export it". Currently it creates an empty file. In french the message should be "Vous devez sélectionner au moins un élément avant de pouvoir l’exporter".

**Comment by cbourget** [comment]
Done
