### ISSUE TITLE
Export GPX or GML fail

### ISSUE THREAD

**Issue by Fr3d3rik777** [infra-geo-ouverte/igo2-lib#292]
**Please tell us about your environment:**

Windows 7, Chrome 73
* **Igo Version:**
1.0.0-alpha

- GPX export does not work, it creates a .gpx file but does not contain anything.
- The exported GML file contains data but is not valid.

**Comment by cbourget** [comment]
This is fixed. The new export behavior is to use the Ogre API if it's available as it supports more file and version types.
