### ISSUE TITLE
WMS legend zoom level

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#299]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1

* **Node:**

The legend of the wms layers should consider the current zoom level and refresh itself when it changes.

**Comment by pelord** [comment]
Should be closed.

**Comment by cbourget** [comment]
Closing wiht PR #300.  https://github.com/infra-geo-ouverte/igo2-lib/pull/300
