### ISSUE TITLE
Directions not working properly in 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#301]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

1- Labels for START, END And INTERMEDIATE not shown on map. Due to the new approach to manage overlays.
2- Adresses proposal is not effective. Refer to issue #302

**Comment by mbarbeau** [comment]
d7d34e58706e644c5caf780814db1d2d1a93ee84
