### ISSUE TITLE
Search by coordinates  1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#302]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

In 1.0.0-alpha.1, the search by coordinates do not work at all. Impact on Directions tool, for adresses proposal.

**Comment by pelord** [comment]
Ok. I forgot to provide the ...ReverseSearchSource . 

But there is still something that I don't understand.

into config.json how to control the url used for reverse search if the URL differ for these 2 services?
At this moment, only searchUrl?: string; is supported.

**Comment by cbourget** [comment]
The two sources have different config. ICherche 's is under 'icherche'. Reverse ICherche's is under 'icherchereverse'.
