### ISSUE TITLE
Queried layers (added from catalog)  1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#304]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

Added layers from catalog, when they are queried, results are grouped into a group named "Carte" instead of the layer name. 

![image](https://user-images.githubusercontent.com/7397743/56660869-7bbe1000-666e-11e9-9e0d-aadf67418382.png)

**Comment by pelord** [comment]
@mbarbeau . Is this issue has been fixed in the current version of 1.0.0-alpha?

**Comment by mbarbeau** [comment]
Yes it's fixed
