### ISSUE TITLE
Search-selector 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#305]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

I think it's would be interesting to clear the previous result when changing the search-selector.

**Comment by cbourget** [comment]
I think both behavior are acceptable so I would leave that to the parent component. The search-selector and search-bar emit an event when the search type changes. They can be used to achieve that.

**Comment by pelord** [comment]
I think we could keep it as proposed initialy. @mbarbeau  ?

**Comment by pelord** [comment]
Ok. Leave it to the parent component, to manage the event.
