### ISSUE TITLE
Zoom behavior on feature selection 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#308]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

Avoid to always/frequently zoom to feature if the feature is contained in the view extent.

**Comment by cbourget** [comment]
I made a few changes to the default behavior a few weeks ago. 
The selection strategy (responsible for the zoom) is more easily configurable.

Did you get a chance to test that recently? Is it acceptable or does it need further improvements?

**Comment by pelord** [comment]
I will test it soon (i.e. this afternoon)
