### ISSUE TITLE
Legend properties on wms-datasource 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#309]
**Please tell us about your environment:**

* **Igo Version:**
 1.0.0-alpha.1
* **Node:**

If we alter the legend property (into the code) to preserve the legend state (collapsed, expanded...) the legend is not shown anymore. 

Due to :

https://github.com/infra-geo-ouverte/igo2-lib/blob/9b7937337052258cf2995ee06ce5365973c9608c/packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts#L160

**Comment by pelord** [comment]
@hugbe8 Does your incoming PR will fix it?

**Comment by hugbe8** [comment]
May be, i check this.
