### ISSUE TITLE
Lower layer 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#310]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

Lower layer below baselayers when "excludeBaseLayers": true should not be allowed.

**Comment by pelord** [comment]
![2019-04-24_09-47-37](https://user-images.githubusercontent.com/7397743/56664451-1a01a400-6676-11e9-898c-373d7204a49c.gif)

**Comment by pelord** [comment]
Could be done into the roadmap 1.1 @mbarbeau

**Comment by mbarbeau** [comment]
4fbe5c47c1836f2dd62fc766830a4ed5542007e0
