### ISSUE TITLE
Mobile : harmonize media.service behavior to css mobile state.  1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#313]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

Media.service propagate media value and values used into CSS are not synchronized. We cannot rely on media service to control content as CSS does. 

Refer to:

https://github.com/infra-geo-ouverte/igo2-lib/blob/fc905d4db2e51c7134c120a7ffd1a7fa1aa70c90/projects/geo/src/lib/map/map-browser/map-browser.component.scss#L20

**Comment by cbourget** [comment]
What is this task about exactly?

**Comment by pelord** [comment]
I've try to control a button visibility by media.service and another by css. Results are incoherent.

**Comment by cbourget** [comment]
You mean the JS ans CSS breakpoints are not the same?

**Comment by mbarbeau** [comment]
#b4262f24569e02ed2645deb22d9f38026b073f20
