### ISSUE TITLE
Search- selector -  Swap from radio button to checkbox for search groups

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#348]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1

1. Change the current radio button by checkbox and add a way to check/uncheck all search-selector
2. Manage the search-selector by search-source instead of search-type

**Comment by cbourget** [comment]
We should not change it. Instead, allow radiobuttons OR checkboxes. The default behavior may be to use one or the other.

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/375
