### ISSUE TITLE
Vector Tiles - Provide a way to toggle multiple style

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#356]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha

Add the support for MVT datasources. 
Style theses sources
Provide a way to toggle multiple style. i.e. day style vs night style.

**Comment by pelord** [comment]
This datasource has been added into alpha with PR #360

**Comment by pelord** [comment]
Still remaining:

Provide a way to toggle multiple style. i.e. day style vs night style.

**Comment by matrottier** [comment]
implement that : https://github.com/openlayers/ol-mapbox-style

**Comment by matrottier** [comment]
see #444

**Comment by mbarbeau** [comment]
Can it be closed?

**Comment by pelord** [comment]
I think it's a cool enhancement, but it's far from a top 1 priority.

**Comment by pelord** [comment]
@infra-geo-ouverte/depot-central-igo 
It's not a feature that I need for the 1.3 release. Do we report it?

**Comment by gignacnic** [comment]
+1 for a report.

**Comment by pelord** [comment]
Closed due to inactivity.
