### ISSUE TITLE
Move layer's tool to a panel into the layer's list

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#357]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha

Button/feature/component multiplication inside the layers list is sometime harassing/non functional

The proposal is to create a panel at the bottom of the list of layers to group this tool inside the panel and access to these tool by click on more_horiz button. 

The include tool a this time: layer opacity, layer upward/downward and filters (ogc and temporal)

**Comment by pelord** [comment]
Here the proposal 

![image](https://user-images.githubusercontent.com/7397743/68480754-8e132c00-0203-11ea-9e56-8d0735378d28.png)

**Comment by ameliebernier** [comment]
I suggest that the filters appear at the bottom too, instead of under each layer. I think the space under each layer should be reserved for the legend, with a button to expand or collapse them all.

**Comment by pelord** [comment]
+ 1

**Comment by ameliebernier** [comment]
Inclus dans https://github.com/infra-geo-ouverte/igo2/issues/397
