### ISSUE TITLE
Make the layer list support drag'n drop 

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#358]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha

Make the layer list manage drag and drop to change the layer order
Should be reporter to 1.2 or 1.x also.

**Comment by pelord** [comment]
I've tried and at this moment, there is an issue with parent to child argument passing for drag'n'drop handle. 

https://github.com/angular/components/pull/13360#issuecomment-463137794

**Comment by mbarbeau** [comment]
Will not be done. An alternative will be found.
