### ISSUE TITLE
param FEATURE_COUNT in double in getFeatureInfo call

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2-lib#364]
On call make by IGO on a layer not in context (add by catalogue or search)  the param FEATURE_COUNT appear twise. That cause some error on particular service.

Exemple:
call make by IGO with double param:

https://serviceswebcarto.mern.gouv.qc.ca/pes/services/Territoire/SDA_WMS/MapServer/WmsServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=R%C3%A9gion%20administrative&layers=R%C3%A9gion%20administrative&feature_count=5&INFO_FORMAT=text%2Fhtml&FEATURE_COUNT=5&X=50&Y=50&CRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-8147113.699602538%2C6187131.402080364%2C-7900069.224184847%2C6434175.877498054

Same call with just 1 param feature_count:
https://serviceswebcarto.mern.gouv.qc.ca/pes/services/Territoire/SDA_WMS/MapServer/WmsServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=R%C3%A9gion%20administrative&layers=R%C3%A9gion%20administrative&INFO_FORMAT=text%2Fhtml&FEATURE_COUNT=5&X=50&Y=50&CRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-8147113.699602538%2C6187131.402080364%2C-7900069.224184847%2C6434175.877498054

**Comment by pelord** [comment]
Fixed in master

**Comment by pelord** [comment]
Fixed by https://github.com/infra-geo-ouverte/igo2-lib/pull/519
