### ISSUE TITLE
Result Features as only one feature

### ISSUE THREAD

**Issue by drekss** [infra-geo-ouverte/igo2-lib#387]
The result of a query only show the last feature of the features list returned by doQueryFeatures.
When 2 layers are queried only one result shows on the result list.
The result only has more than one feature if the layers are wms, wmts or wfs.

**Comment by matrottier** [comment]
have you made any progress on this?

**Comment by matrottier** [comment]
see : pull request #401 commit dfc8a62a22932b0e4e06d48ea1bf307cc48ff5e0
