### ISSUE TITLE
Catalog layers offset

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#423]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0

* **Node:**

In IGO 1.0.0, catalog icons have been removed. Now, first level layers (not in a group) are shown like this:

![image](https://user-images.githubusercontent.com/2046987/65521659-8d267500-deb7-11e9-9a9d-64e06cdcc088.png)

Layers that do not belong to a group should occupy the full width.

**Comment by pelord** [comment]
@hugbe8  - Is it still an issue?

**Comment by hugbe8** [comment]
Resolved in pullRequest #559
in file: packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.html
