### ISSUE TITLE
Query cascade with error

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2-lib#447]
**Please tell us about your environment:**
Chromuim Version 76.0.3809.100 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits

* **Igo Version:**
1.0

when a error occur in one of the queries, all the successful queries are ignored.
works must be done in the [query.directive](https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/query/shared/query.directive.ts#L161)

**Comment by josee666** [comment]
@matrottier est-ce toujours un problème?
