### ISSUE TITLE
Idea: modal slider on opacity button

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2-lib#451]
**Please tell us about your environment:**
* **Igo Version:** 1.0

Idea: for the interface of the opacity slider. For saving space in screen. There could be appear a modal panel on button. The% could be kept on the button after setting.

Sample:
![image](https://user-images.githubusercontent.com/1155637/66153676-f27e1280-e5e9-11e9-9395-2b0ab26ff0eb.png)

Material icon [available](https://materialdesignicons.com/): 
brightness-5, lightbulb-on-outline, weather-sunny, weather-sunset, white-balance-sunny, sunglasses

**Comment by mbarbeau** [comment]
I close, linked to https://github.com/infra-geo-ouverte/igo2/issues/397
