### ISSUE TITLE
CatalogBrowser tool title

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#461]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0

When navigating inside a catalog, the generic tool name is shown into the tool title section for the CatalogBrowser tool.

It would be nice if the catalog title were shown into the CatalogBrowser tool title. 

Here, inside the "Forest" catalog.
In this case, replace the title "Catalog" by "Forest"

![chrome_2019-10-08_12-38-39](https://user-images.githubusercontent.com/7397743/66415095-bc190c80-e9c8-11e9-905a-5cd918a3e3f9.png)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2/pull/416
