### ISSUE TITLE
Zoom on map

### ISSUE THREAD

**Issue by mickjol** [infra-geo-ouverte/igo2-lib#47]
How I can block "zoom in" and "zoom out" ?

When I "zoom in", at some point I doesn't have access to map. So all image are white.
Can I setup a minimum zoom and a maximum zoom.

**Comment by cbourget** [comment]
You can set "minZoom" and "maxZoom" properties in the map view context. "minResolution" and "maxResolution" are also supported. See https://openlayers.org/en/latest/apidoc/ol.View.html for more information.
