### ISSUE TITLE
icherche reverse distance options

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#474]
* **Igo Version:**
1.0.0

The iCherche distance options is not used.

https://github.com/infra-geo-ouverte/igo2-lib/blob/56e45cdb030d39d1637ddfaf81f07e65345dcd89/packages/geo/src/lib/search/shared/sources/icherche.ts#L493

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/commit/5fb8a3b0ee826ad32c156dceef7e2391022c75a9
