### ISSUE TITLE
keyCode access is deprecated

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#484]
* **Igo Version:**
1.0.0
* **Node:**
10.15.1

combineLatest is deprecated: Pass arguments in a single array instead `combineLatest([a, b, c])`
- igo2-lib/packages/geo/src/lib/feature/shared/strategies/selection.ts:154:21
- igo2-lib/packages/core/src/lib/language/shared/language.loader.ts:34:21
- igo2-lib/packages/common/src/lib/entity/shared/view.ts:191:12
- igo2-lib/packages/common/src/lib/entity/shared/view.ts:187:37
- igo2-lib/packages/common/src/lib/entity/shared/view.ts:165:21

 addListener is deprecated.
- igo2-lib/demo/src/app/app.component.ts:28:22

removeListener is deprecated.
- igo2-lib/demo/src/app/app.component.ts:34:22

**Comment by pelord** [comment]
igo2-lib/packages/common/src/lib/list/list.component.ts:73:24 - keyCode is deprecated.

**Comment by pelord** [comment]
combineLatest fixed. Remaining keycode.

**Comment by mbarbeau** [comment]
Fixed in https://github.com/infra-geo-ouverte/igo2-lib/tree/1.5.0-alpha.1
