### ISSUE TITLE
problem on call v1.1.1 service, param SRS vs srs

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2-lib#489]
problem on call of particular service in version 1.1.1
* same problem on catalog and context
** check the getFeatureInfo have to work too

in config for a old service we have to put parameter version ans srs. If the parameter srs is in lower case, the call doesn't work. If the param SRS is in capital lettre, the call work.

Exemple 1: DOESN'T work
CONFIG (srs in lower)
        {
          id: '4',
          title: 'SIGEOM',
          url: 'https://servicesvectoriels.atlas.gouv.qc.ca/IDS_SGM_WMS/service.svc/get?',
          crossOrigin: true,
          version: "1.1.1",
            queryFormat: {
            html: '*'
            },
            queryParams:{
              srs: 'EPSG:3857'
      } 
CALL = 
https://servicesvectoriels.atlas.gouv.qc.ca/IDS_SGM_WMS/service.svc/get?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&srs=EPSG%3A3857&layers=SGM%3AMines_projets&version=1.1.1&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&SRS=EPSG%3A3857&STYLES=&WIDTH=1088&HEIGHT=450&BBOX=-8792092.741474112%2C5699144.828942741%2C-7461476.953085765%2C6249491.43259601

Exemple 2, WORK fine

CONFIG (SRS in capital)
        {
          id: '4',
          title: 'SIGEOM',
          url: 'https://servicesvectoriels.atlas.gouv.qc.ca/IDS_SGM_WMS/service.svc/get?',
          crossOrigin: true,
          version: "1.1.1",
            queryFormat: {
            html: '*'
            },
            queryParams:{
              SRS: 'EPSG:3857'
      } 
    }

CALL=
https://servicesvectoriels.atlas.gouv.qc.ca/IDS_SGM_WMS/service.svc/get?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&SRS=EPSG%3A3857&layers=SGM%3AMines_projets&version=1.1.1&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&STYLES=&WIDTH=1088&HEIGHT=450&BBOX=-8792092.741474112%2C5699144.828942741%2C-7461476.953085765%2C6249491.43259601

**Please tell us about your environment:**
chrome 77.0

* **Igo Version:**
master from 29 october AM

**Comment by pelord** [comment]
Fixed in master

**Comment by pelord** [comment]
Fixed by https://github.com/infra-geo-ouverte/igo2-lib/pull/519
