### ISSUE TITLE
Load context on cordova

### ISSUE THREAD

**Issue by mickjol** [infra-geo-ouverte/igo2-lib#49]
The _contexts.json does not load on cordova.

Can I change the basePath where to all context file ?

**Comment by cbourget** [comment]
Yes, in your app.module.ts file, you can provide different context service options by calling the "provideContextServiceOptions" function like this:

```
provideContextServiceOptions({
    basePath: './base/context/path',
    contextListFile: 'all_contexts_file.json'
})

```

You may also define your contexts programatically and use "contextService.setContext" instead of "contextService.loadContext" if that suits you better.

**Comment by mickjol** [comment]
OK good, now my context file is loading "_default.json" with my basePath as "./contexts".

But in my cordova project, the map work only in browser mode (cordova run browser).
On android (cordova run android) and iOS (cordova run ios) the map doesn't load (everything stay white)

**Comment by cbourget** [comment]
I'm not very familiar with Cordova but I can look into it later. For now, if you need a quick fix, have you tried to set your context programmatically instead of loading it from a file, like I explained in the first post? Also, do you have any error log that I could work with?

**Comment by cbourget** [comment]
Before doing what I suggested in my previous post, try to remove any underscore "_" from your context file names. "_default.json" -> "default.json" and "_contexts.json" -> "contexts.json".

**Comment by cbourget** [comment]
Did any of these suggestions work?

**Comment by mickjol** [comment]
contextService.setContext work
I did not try to remove underscore on my file

**Comment by cbourget** [comment]
Good. If you want to try and remove the underscore, it'd be very interested to know if it works.

**Comment by mickjol** [comment]
I still have the problem after removing the underscore.

**Comment by cbourget** [comment]
Thank you
