### ISSUE TITLE
Use store.stateView in entity tables

### ISSUE THREAD

**Issue by cbourget** [infra-geo-ouverte/igo2-lib#492]
**Please tell us about your environment:**

* **Igo Version:**

* **Node:**

The current implementation of the entity table is connected to its store's view. This is acceptable but it doesn't allow us to things like displaying selected entities only (because selected is set in the stateView, not the view).

In order to use the staeView, we'll need a bit of optimization because, we don't want en entity table to rerender itself entirely when the state of an entity changes. To do that, we'll take advantage of the trakBy feature of angular material tables. To do that, we'll a need a way to identify uniquely the stateView records and to know when a record changed.

**Comment by pelord** [comment]
@cbourget Any updates?

**Comment by pelord** [comment]
@danlav01 . Du nouveau. 

On ferme et on ouvrira au besoin.
