### ISSUE TITLE
query example does not work.

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2-lib#499]
**Please tell us about your environment:**
Version 77.0.3865.90 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits)

* **Igo Version:**
branch master

* **Node:**
v10.7.0

query exemple does not work.
something about "sourceOptions" do not work anymore

**Comment by PhilippeLafreniere18** [comment]
Just seems to be a conflict in query demo when layers are being created and added to the map : layer.options.souceOptions become layer.options.source.options.

Works just fine in igo2 (assemblage).
