### ISSUE TITLE
Legend display

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2-lib#507]
I think that it may not be easy to find a layer's legend. Should we bring back the arrow at the left and keep the interaction with the layer name to expand/close the content? The arrow would show that there is an expandable content. The catalog could have the same behaviour as well as any list element with expandable content.

I know it was a space issue but I think it can be easily overlooked and the user would search for the legend.

**Comment by cbourget** [comment]
Or, we could add a button that toggles all the layers legend at once? This would save the user quite a few clicks if he wants to see the whole legend.

**Comment by ameliebernier** [comment]
At the top? What is this button for 
![image](https://user-images.githubusercontent.com/45005853/68424248-93c03180-0171-11ea-8ad1-6367c7fd11df.png)

**Comment by cbourget** [comment]
I think it's used to show only the layers in range (resolution). Yes, I think I would put it at the top.

**Comment by ameliebernier** [comment]
Is there still a need to see the legend for only one layer? There is a lot going on in this section with the filters, etc.

**Comment by cbourget** [comment]
Personnally, I think we should show all the legend or not show it all but the status quo is acceptable (or, like you suggested, maybe add an arrow icon). It's true that there may not be enough room for another button at the top of the list.

**Comment by ameliebernier** [comment]
Or replace the button to filter the layers in range?

**Comment by ameliebernier** [comment]
I was thinking about the fact that the filters (attributes and time) are now displayed uner the name of the layer, so if you have several filters and then also display the legend of all layers it could be too much

**Comment by cbourget** [comment]
That's a possibility to explore. Adding @pelord to this conversation.

Maybe we shouldn't show the filter input all the time and add a toggle button for it. That would free some room.

**Comment by pelord** [comment]
> At the top? What is this button for
> ![image](https://user-images.githubusercontent.com/45005853/68424248-93c03180-0171-11ea-8ad1-6367c7fd11df.png)

This buttons stands for remove from the layer list the layer not available at the current scale. 

Furthermore, this toolbar need to be fixed due to an issue between transition from 0.X version to 1.0.0 version. 

About modifying the whole behave of the legend/options, @mbarbeau , @josee666, @gignacnic @danlav01, @VP08   identified a way to manage the options/tools. Something like ...

![image](https://user-images.githubusercontent.com/7397743/68480644-4db3ae00-0203-11ea-97e7-f6c7fd79d762.png)

At this moment, some free space will allow to propose an alternative method to access the legend.

This new feature is plan in the 1.2 roadmap.
Refer to https://github.com/infra-geo-ouverte/igo2-lib/issues/357

**Comment by ameliebernier** [comment]
Interesting, should the filters appear at the bottom too, instead of under each layer. I think the space under each layer should be reserved for the legend, with a button to expand or collapse them all.

Aussi pour être consistent avec le reste de l'application (catalogue, résultats de recherche), la section du bas devrait-elle s'afficher quand on clique sur un layer?

**Comment by pelord** [comment]
Interesting, should the filters appear at the bottom too, instead of under each layer. I think the space under each layer should be reserved for the legend, with a button to expand or collapse them all.

Yes.

**Comment by pelord** [comment]
Aussi pour être consistent avec le reste de l'application (catalogue, résultats de recherche), la section du bas devrait-elle s'afficher quand on clique sur un layer?

A envisager.

**Comment by ameliebernier** [comment]
Should we address the legend in version 1.2? It seems to go with #357 and we shouldn't stay too long without

**Comment by pelord** [comment]
You should create an issue. A discussion must be done will all contributor because it's look like a roolback to bring back the caret to toggle the legend.

**Comment by ameliebernier** [comment]
This is the issue

**Comment by pelord** [comment]
:)

**Comment by josee666** [comment]
Pour ce qui est de la légende, de notre coté la configuration active d'ouvrir la légende automatiquement lorsqu'on active la couche semble satisfaisante pour l'instant.
NB: Je crois que certains contextes ne se prêtent pas bien a l'ouverture de toutes les légendes en un clic:
Exemple chez nous nous avons un contexte avec 71 couches et nos légendes sont souvent complexe
 -> plusieurs élément qui prennent beaucoup d'espace (surtout en mobile)
Dans ce cas je ne crois pas que de les ouvrir toutes dans un coup sera gagnant... Serait même à proscrire. De plus, quel sera la performence de ceci sur 71 getLegend....

**Comment by ameliebernier** [comment]
Inclus dans https://github.com/infra-geo-ouverte/igo2/issues/397
