### ISSUE TITLE
Having the possibility to add an entity with the map query tool to the current query results

### ISSUE THREAD

**Issue by cotji1** [infra-geo-ouverte/igo2-lib#508]
There's already a possibility to select multiple entity from a layer using ctrl + left click + drag

it would be interesting to be able to add to the current selection.

As for example: I select a first set of entites using ctrl + left click

I could then either cancel that selection clicking anywhere else on the map
or add to the selection set with an other ctrl + left click

**Comment by cbourget** [comment]
How is configured your layer? Is it a layer that comes from a context?

This is already possible when using a FeatureStore and FeatureStoreSelectionStrategy.

**Comment by cotji1** [comment]
I add my layer not using the import layer feature in IGO.
I use the map.addLayer method

My  layer is a vectorLayer with featureDataSource(QueryableDataSource).
 I then assumed  that IGO would handle the selection part.

**Comment by cbourget** [comment]
IGO does allow you to make a selection but it needs more than a layer added. Also, there must something you want to do once a selection is made?

The feature store and the selection strategy might help you. A store enables useful features and is an efficient development pattern.

**Comment by cotji1** [comment]
I should of use map query tool and query results instead of selection and selection set.

**Comment by cotji1** [comment]
![image](https://user-images.githubusercontent.com/49662343/68505107-7607d080-0234-11ea-80ce-c802e14d7aaf.png)

**Comment by pelord** [comment]
@gignacnic Any update about this issue?

**Comment by pelord** [comment]
Close due to inactivity
