### ISSUE TITLE
Having the possibility to choose coordinates format in the search box

### ISSUE THREAD

**Issue by cotji1** [infra-geo-ouverte/igo2-lib#509]
It is possible to search with a Decimal Degrees coordinates.

It would be usefull to be able to choose witch format to use, and the system could propose  an input mask.

- Decimal Degrees coordinates
- Degrees Minutes Seconds

**Comment by mbarbeau** [comment]
It is already possible to search in degrees minutes seconds.
Example: 43° 22' 11" N, 71° 41' 41" W

But the format is very severe. It could be easily improved to be more user-friendly.
