### ISSUE TITLE
replace time-filter-item alert icon by the eye

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2-lib#515]
* **Igo Version:**
1.1.0

now :
![time-filter_before](https://user-images.githubusercontent.com/5638601/69168346-7de13380-0ac4-11ea-8726-3cae800219a7.png)
after :
![time-filter_after](https://user-images.githubusercontent.com/5638601/69168344-7c177000-0ac4-11ea-80a2-e50a10dd6297.png)

**Comment by pelord** [comment]
It can also be done in ogcFilter tool.

**Comment by mbarbeau** [comment]
Fait dans:
https://github.com/infra-geo-ouverte/igo2-lib/pull/625
