### ISSUE TITLE
Coordinates are flipped oudside north america.

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#528]
* **Igo Version:**
1.1.0

When using contextual menu to make a reverse search, result outside north-america are wrong/flipped/inverted.

![image](https://user-images.githubusercontent.com/7397743/70367191-cc842100-186b-11ea-83e8-7bd40a9903ff.png)

**Comment by mbarbeau** [comment]
Fix by this commit: f5c959d30b5f91ad7f1164e47e058207a058df41
New forceNA options on search-bar.component if we want reverse the coordinates. Default: false
