### ISSUE TITLE
Panels masks features when zooming

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2-lib#532]
* **Igo Version:** 1.1

Le panneau latéral ou le panneau du getinfo peuvent masquer les features quand il y a un zoom automatique fait par l'application (par exemple, avec l'outil "zoomer sur l’itinéraire", le point de départ se retrouve souvent masqué).

Il faudrait pouvoir ignorer l'espace occupé par les panneaux quand un zoom est effectué

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2/commit/675279ef0d678d5d66deba35b0f35884cdaf853c
