### ISSUE TITLE
Time filter calendar control enhacements

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2-lib#534]
* **Igo Version:** 1.1

Three proposed enhacement for the calendar control in time filter tool : 

- [ ] We should be able to set the date manually (at the moment we can only use the calendar)

- [x]  Calendar should show the currently selected date

- [ ]  The date should be in correct format according to locale (actually displays as MM/DD/YYYY in french-ca locale, should be YYYY-MM-DD)

- [ ]  Possibility to remove date (for example, end date of filter is undefined, so every features after start date are displayed)

- [x] Calendar icon should align correctly above the input line

![image](https://user-images.githubusercontent.com/45005853/71007398-f1229900-20b4-11ea-9ff4-75d98c68aa84.png)

- [x] When defining a min date for timeFilter param in context, the day before is available in the calendar, However if this date is chosen the control remains invalid. Exemple with min date of time filter = 1990-01-01 : 1989-12-31 is available in calendar, but control is invalid if selected

![image](https://user-images.githubusercontent.com/45005853/71008765-27611800-20b7-11ea-9363-0ac890172572.png)

**Comment by PhilippeLafreniere18** [comment]
Point 2, 5 et 6 réglé avec pull request #621.

**Comment by mbarbeau** [comment]
in my opinion the format "DD/MM /YYYY" is correct
