### ISSUE TITLE
Catalog item constructor not manage nested groups

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2-lib#565]
**Please tell us about your environment:** Chrome Version 79.0.3945.130

* **Igo Version:** master (1.1.0)

The catalog item constructor does not manage nested groups. Result, the subgroups are not available for later display including the layers which if reports.

**QGIS - WMS connexion:**
![image](https://user-images.githubusercontent.com/1155637/73210280-eaf1f480-4117-11ea-9187-5d0b3f0b5f39.png)

**Relate:** fix(catalog): recursive loop on wms groups on prepare object for catalog. [pullRequest 559](https://github.com/infra-geo-ouverte/igo2-lib/pull/559)
Prerequis for issue: [564](https://github.com/infra-geo-ouverte/igo2-lib/issues/564)

**Comment by pelord** [comment]
@PhilippeLafreniere18 I will take care of groups in Esri Services
