### ISSUE TITLE
When unchecking all search sources, the results stay into the result tool

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#590]
* **Igo Version:**
1.2.0

When unchecking iLayer search sources, the results stay into the result tool

Here the visual explanation:
(from https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/)

![2020-02-28_13-08-27](https://user-images.githubusercontent.com/7397743/75584806-a15e3780-5a3e-11ea-8daa-27f0ddaac2a1.gif)

**Comment by pelord** [comment]
@mbarbeau ,
@PhilippeLafreniere18  

Could you take a look on this?

**Comment by PhilippeLafreniere18** [comment]
It seems to be a problem with the last search source that is displaying, so not related to ilayer directly.

**Comment by mbarbeau** [comment]
Because it has no search source, the search is not launched and the result list is not updated.

**Comment by pelord** [comment]
Fixed by https://github.com/infra-geo-ouverte/igo2-lib/pull/602

**Comment by pelord** [comment]
Included in the next release.
