### ISSUE TITLE
no watcher for mvt datasource layer

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2-lib#592]
Igo2 version 1.2.

Once a context is having a mvt vector tile datasource layer, it is not possible to switch context because mvt datasource layer does have a watcher.
@drekss

**Comment by pelord** [comment]
@gignacnic . Could this bug be closed?

**Comment by pelord** [comment]
@gignacnic still an active issue?

**Comment by gignacnic** [comment]
@drekss is this fixed?

**Comment by pelord** [comment]
@gignacnic  done https://github.com/infra-geo-ouverte/igo2-lib/commit/b3cb8b3
