### ISSUE TITLE
igoPointerPositionByKey randomly triggerred without any keydown

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#605]
* **Igo Version:**
1.2

igoPointerPositionByKey triggerred without any keydown.

**Comment by pelord** [comment]
@infra-geo-ouverte/depot-central-igo  Somebody know how to repeat this issue? I know I have raised the issue! But I don't have any hint how trigger the bug...  :(

**Comment by josee666** [comment]
yes. 2 problem here in version 1.2 in https://pre.foretouverte.gouv.qc.ca
1- with a layer with fill polygone the resume doesn't appear (or apear below layer...)
2- the resume doesn't appear on base map

to replicate:
- activate pointer summary
-activate a fill layer
= problem 1 -> the resume doens't appear and it's activate
-desactivate the fill layer
= problem 2 -> the resume doesn't appear and it's activate (or maybe appear below layer...)
![OoATINrob8](https://user-images.githubusercontent.com/32003632/77531967-41ef1e00-6e6a-11ea-9003-b01d30a63ba3.gif)

**Comment by pelord** [comment]
I think we are not talking about the samedi problem. The pointer summary refer tout reverse source service, not layers.

In this case, when you hold CTRL while moving the cursor on the map, the reverse search is triggered. The issue is relaed to this feature.

**Comment by josee666** [comment]
Ok i put that in a new issus.

**Comment by pelord** [comment]
2 incoming steps

1- remove the directive from the next release
2- investigate to identify the issue.

**Comment by pelord** [comment]
@mbarbeau Could you remove the directive in the next release?
https://github.com/infra-geo-ouverte/igo2/blob/f51500dea28ecce6381b111d01459027d8f35ce1/src/app/pages/portal/portal.component.html#L44

**Comment by mbarbeau** [comment]
This directive is no longer used 8fd4b09b
