### ISSUE TITLE
Get one item of LanguageService

### ISSUE THREAD

**Issue by mickjol** [infra-geo-ouverte/igo2-lib#61]
Can I extract one label of language locale file (language) in typescript.

languageService.get("myLabel") or languageService.getDescription("myLabel")
or for many
languageService.get(["myLabel", "myLabel2"])

I can't place this directly in my HTML.

**Comment by mbarbeau** [comment]
This is not possible at this time. I will make a change soon to be able to extract a translation.

**Comment by mickjol** [comment]
I update to 0.5.1

I'm able to use the LanguageService in my template with {{'name' | translate}}
But when I try to use "LanguageService.translate.instant" I always has this error.

ERROR Error: Uncaught (in promise): Error: LanguageService must be injected

My constructor is like this.
`constructor(private translate: LanguageService) {
    const name = this.translate.translate.instant('name');
}`
