### ISSUE TITLE
min/max scale wms layer

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2-lib#62]
When adding a layer to a map, disable "show" button when min/max scale value does not correspond with OL map.
See value example of max/min scale for a layer in Getcapabilities:
BoundingBox SRS="EPSG:32198" minx="-1.1e+06" miny="-23500" maxx="1.1e+06" maxy="2.2535e+06"

**Comment by mbarbeau** [comment]
See pull request #70


In the JSON, at the layersOptions, you can add these properties
```
view: {
        maxResolution: Number
        minResolution: Number
}
```

Or else, use options from wms with:
`"optionsFromCapabilities": true`
