### ISSUE TITLE
Update depedencies

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#638]
* **Igo Version:**
1.3.0

Update depedencies (depedencies and or dev depedencies)

**Comment by pelord** [comment]
Into 1.4 release?

**Comment by pelord** [comment]
On OL update (ol 6.3.1)
These component crash

- https://infra-geo-ouverte.github.io/igo2-lib/#/feature 
   (ERROR TypeError: "vectorContext is undefined")
- https://infra-geo-ouverte.github.io/igo2-lib/#/query
   getGetFeatureInfoUrl must be replaced by getFeatureInfoUrl
- https://infra-geo-ouverte.github.io/igo2-lib/#/catalog
   TypeError: Cannot read property 'showLegend' of undefined (error was also there in 1.3)
- https://infra-geo-ouverte.github.io/igo2-lib/#/print
   cannot read property 'canvas' of undefined
- https://infra-geo-ouverte.github.io/igo2-lib/#/import-export
  Nothing is shown on map...
- https://infra-geo-ouverte.github.io/igo2-lib/#/spatial-filter
   crash by due to the demo configuration?

**Comment by pelord** [comment]
Not so bad :)
Maybe we should fix TypeError: Cannot read property 'showLegend' of undefined (error was also there in 1.3) in 1.3.1?

**Comment by pelord** [comment]
And 
import stylefunction from 'ol-mapbox-style/stylefunction';
must be replaced by 
import stylefunction from 'ol-mapbox-style/dist/stylefunction';

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/tree/updateOl

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/tree/1.5.0-alpha.1

Everything is up to date.

The last known bugs:

- [ ] During the build: (node:16252) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
- [ ] Import/Export: Features added to the layer are not visible. (only in the lib demo, works in assembly)
- [ ] Spatial Filter: Freehand circle is not visible

**Comment by matrottier** [comment]
OGC Filters did not refresh when updated/deleted.  
tested with node v14.6.0

**Comment by pelord** [comment]
OGC Filters did not refresh when updated/deleted.
Fixed in #705 ,  https://github.com/infra-geo-ouverte/igo2-lib/pull/705/commits/0f5665539f31f37a4df736625e6a952a31220b30

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/696
