### ISSUE TITLE
Allow multiple layers selection on export tool

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2-lib#640]
Allow the user to select multiple or all layers that are active on the map. Actually, you can only export one layer at the time.

**Comment by PhilippeLafreniere18** [comment]
Use multiple option selection : https://material.angular.io/components/select/overview#multiple-selection

**Comment by PhilippeLafreniere18** [comment]
Results with multiple download

**Comment by pelord** [comment]
+1
