### ISSUE TITLE
WFS geojson (EPSG:3857 or other EPSG) not working

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2-lib#645]
**Please tell us about your environment:**
Ubuntu 18.04

* **Igo Version:**
1.3.0

* **Node:**
v12.16.3

WFS-geojson-epsg:3857 do not work. By default OL use EPSG:4326.  
formatOptions is not used in the creation of the ol format [wms-wfs.utils.ts#L129](https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts#L129)

**Comment by pelord** [comment]
@matrottier This is fixed in the current version 1.4 ?

**Comment by matrottier** [comment]
i will try to test next week...

**Comment by matrottier** [comment]
![done](https://media.giphy.com/media/8JW82ndaYfmNoYAekM/giphy.gif)
