### ISSUE TITLE
missing title for wmts layer from catalog

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2-lib#669]
**Please tell us about your environment:** Chrome Version 83.0.4103.97

* **Igo Version:** master (1.3.1)

There are no title applicated on map for the wmts layer coming from catalogue.

IGO2 display:
![image](https://user-images.githubusercontent.com/1155637/84810358-40507480-afd9-11ea-8189-ff5a3c209261.png)

**Comment by pelord** [comment]
@hugbe8 Fixed in the current version (1.4.2 + ) ?
