### ISSUE TITLE
wmts layers not shareable by copy link

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2-lib#670]
**Please tell us about your environment:**

* **Igo Version:** master (1.3.1)

The wmts layers added at map don't are shareable by tool 'copy link'

* **Node:**

**Comment by pelord** [comment]
@hugbe8 This is fixed in the current version (1.4.2 and +)?

**Comment by pelord** [comment]
@hugbe8 This is fixed in the current version (1.4.2 and +)?
