### ISSUE TITLE
wms with 2 layers problem with optionFromCapabilities:true

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2-lib#687]
When you have a wms with 2 layers in layers param if you add param optionFromCapabilities:true 
the getCapabilities doesn't find 'that' layer and the user get a red message in context.

config layer exemple in problem:
{
      "title": "Unité de gestion",
      "zIndex": 6,
      "visible" : true,
      "metadata": {
        "url": "https://www.donneesquebec.ca/recherche/fr/dataset/stf",
        "extern": "false"
        },
      "sourceOptions": {
        "queryable": true,
        "queryFormat": "geojson",
        "crossOrigin": "anonymous",
        "queryHtmlTarget": "iframe",
        "url": "https://servicescarto.mern.gouv.qc.ca/pes/services/Forets/STF_WMS/MapServer/WMSServer?",
        "params": {
            "layers": "Unité gestion,Unité gestion - 1M"
        },
        "type": "wms" ,
       "optionsFromCapabilities": true   
      }
    },

* **Igo Version:**

1.3.1

**Comment by pelord** [comment]
Another way find to handle this. @josee666  explaination please.
