### ISSUE TITLE
Print-tool: Titre trop long ne s'ajuste pas

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2-lib#724]
- Quand un titre est trop long et qu'on enregistre au format PDF, celui-ci ne s'ajuste pas dans la carte résultante

- Devrait s'étaler sur le nombre de lignes suffisantes ou encore diminuer la taille de la police afin qu'on puisse voir le titre au complet

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/805
