### ISSUE TITLE
Share-map tool : un changement de zoom n'actualise pas l'URL de partage

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2-lib#726]
- Si on partage une carte dans l'outil et que le lien est généré, celui-ci ne s'actualise si un changement de zoom est fait. Il a besoin de changer d'outil, puis de revenir dans l'outil de partage pour s'actualiser.

**Comment by pelord** [comment]
Semble fonctionner. 
Provient de la demo github. 
![RQpzg333DO](https://user-images.githubusercontent.com/7397743/97372399-ef576380-1889-11eb-90cf-885a6b3dc83b.gif)

**Comment by PhilippeLafreniere18** [comment]
@mbarbeau seulement besoin d'être merger dans la dev alors ?

**Comment by mbarbeau** [comment]
fixed by ec194745
