### ISSUE TITLE
Is there a way to highlight features in queried layer?

### ISSUE THREAD

**Issue by sukeshlaghate** [infra-geo-ouverte/igo2-lib#742]
I have a 

- [x] Question
- [ ]  Bug
The Demo app for querying feature show details about the feature clicked. However, there is no way to visually discern which feature was queried for. My question is: Is there a way to highlight queried feature in layers shown in map? If so how can i enable highlighting?

to illustrate please refer to attached screen shot.
![igo2-query-screenshot](https://user-images.githubusercontent.com/25061957/95558542-00a01380-0a34-11eb-8baf-aa1e7694f6f9.png)

I would expect feature to be highlighted
 Would appreciate any pointers or solution.

**Please tell us about your environment:**

**OS:** Ubuntu
**Browser:** FireFox 81.0 (64-bit), Chrome 86.0.4240.75 (64-bit)
* **Igo Version:** 1.4.3

* **Node:** v13.14.0

**Comment by mbarbeau** [comment]
Hi, the demo is very simplified. Of course, you can highlight the feature clicked.

The easiest way is to use the map overlay by adding at the end of the 'handleQueryResults' function:
this.map.overlay.setFeatures([feature], FeatureMotion.None); 

'FeatureMotion' must be imported from @igo2/geo. Allows you to indicate whether you want to zoom in on the feature, move around it or do nothing after adding the feature.

**Comment by sukeshlaghate** [comment]
Thank you @mbarbeau  for quick response.

Solution suggested by you would work for WFS layers. In case of WMS, I believe we would need to pass SLD to Geoserver/MapServer to highlight the clicked feature. Is there any provision to send this SLD? If yes, where can I specify this SLD, in source options or somewhere else.
 
Follow up question: Where can I find api documentation/cookbook (in English :smile: )? 
That way any new user can familiarize themselves with igo2 tips and tricks to achieve intended functionality.

**Comment by mbarbeau** [comment]
SLD is not required, in the demo there is a WMS.
If the return of getFeatureInfo has geometry, it will be used to highlight the selected feature.
Unfortunately, the documentation in English is not yet done. :disappointed:

**Comment by sukeshlaghate** [comment]
@mbarbeau Thank you for answering. I am marking this closed.
