### ISSUE TITLE
How to work with the store and state

### ISSUE THREAD

**Issue by moonlik** [infra-geo-ouverte/igo2-lib#749]
Hi!

I've tried to find any explanation about how to work with the [`store`](https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/feature/shared/store.ts) and how I should work with the [`state`](https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/common/src/lib/entity/shared/state.ts), but I can't find it anywhere. Could anyone recommend any resources related to it or maybe anyone could briefly clarify some points for me?

**Comment by mbarbeau** [comment]
Hi,

You have some information on the use of store and state here:
https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/common/src/lib/entity/shared/store.md

If you have more specific questions, do not hesitate to contact us again.

**Comment by moonlik** [comment]
@mbarbeau thank you!

Actually, I don't clearly understand what is the difference between `update()` and `insert()` in the [`store`](https://www2.hm.com/en_asia3/productpage.0750055007.html). 

For me, it seems that: when I want to insert a new **entity** to the store I use this `insert()` method, and then if I want to _change_ or _modify_ this **entity** I should use `update()` method. But in the source code of the [`store`](https://www2.hm.com/en_asia3/productpage.0750055007.html), both methods are the same. Or maybe I shouldn't update the `store`, but should update the [`state`](https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/common/src/lib/entity/shared/state.ts) when I want to make a modification?

**Comment by cbourget** [comment]
You're right that insert and update do the same thing; they replace the entity with a matching key in the store with the one provided to the method. The store doesn't know how to update an entity by itself. This might be the job of a service, for example. What it knows is that for a key X there is an entity Y. Replacing (update) the entity at X triggers some observables.

The state of the store is a different thing. The state holds the state of every entity in the store. For exemple, an entity may become "selected" or "active" after a mouse click. The state is the place to keep that information. Changing the state also triggers some observables that other parts of your code or UI may react to.

**Comment by pelord** [comment]
@moonlik . Shall we close this issue?

**Comment by moonlik** [comment]
@cbourget 
Ok, thank you. I will try it.

@pelord 
Ok, sure.
