### ISSUE TITLE
wms-t filter

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2-lib#77]
When you filter your wms service by the time slider and afterward navigating to another menu e.g. Results and we come back to time slider menu, we loose the two date that were picked up previously.

**Comment by matrottier** [comment]
@pelord is it fixed ?

**Comment by gignacnic** [comment]
I think so, if you try the same behaviour here: https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=embacle, the date are still there when navigating from a menu to the other...

**Comment by pelord** [comment]
Yes. This issue is fixed.
However, it's seem to be not possible to clear the filter? Values (dates) are still there despite when you click on the (X) button to clear.
