### ISSUE TITLE
Message service options do not change simple notifications

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2-lib#782]
Passing options to message service (as icon) don't change the notification. Seems to be blame on the latest version of angular notification / simple notifications. 

https://github.com/flauc/angular2-notifications

**Comment by pelord** [comment]
@PhilippeLafreniere18  Must be fixed by https://github.com/infra-geo-ouverte/igo2-lib/commit/01d5eefb65c3dcfcceca77eb835d3c4fa000253b

**Comment by pelord** [comment]
Linked to https://stackoverflow.com/questions/49774566/simple-notifications-options-dont-set ?

**Comment by PhilippeLafreniere18** [comment]
Resolve with new message library ? @pelord

**Comment by pelord** [comment]
Yes. Refer to a css class instead. 
https://github.com/scttcper/ngx-toastr#individual-options
