### ISSUE TITLE
adding an image on vector markers

### ISSUE THREAD

**Issue by tmmschmit** [infra-geo-ouverte/igo2-lib#791]
Hello I'm trying to customize my markers to have an icon (png or svg) for the base state and another for the "selected" state.

I followed on of your examples (https://github.com/infra-geo-ouverte/igo2-lib/tree/master/demo/src/app/geo/feature),
and have a layer that looks like: 
```
    this.dataSourceService
      .createAsyncDataSource({
        type: 'vector',
      })
      .subscribe(dataSource => {
        const layer = this.layerService.createLayer({
          title: 'Vector Layer',
          source: dataSource,
          sourceOptions: {
            queryable: true,
          },
          // styleByAttribute: {
          //   icon: ['assets/images/marker.png'],
          //   attribute: 'default_marker',
          //   data: ['true', 'false'],
          //   width: [2, 2],
            
          // }
          // "icon-image": {
          //   "default": "default_marker",
          // },
          // "sprite": "assets/sprites.json"
          // animation: {
          //   duration: 2000
          // },
          mapboxStyle: {
            url: 'assets/mapboxStyle.json',
            source: 'source_nameX'
          }
        } as any) as VectorLayer;
        this.map.addLayer(layer);
        this.store.bindLayer(layer);
        loadingStrategy.activate();
        selectionStrategy.activate();
      });
```

Il load my markers via `this.store.load(entitiesList);`
    
my **mapboxStyle.json** look like: 

   ```
{
    "version": 8,
    "name": "Style",
    "sources": {
        "source_nameX": {
            "type": "vector",
            "minZoom": 0,
            "maxZoom": 22
        }
    },
    "layers": [
        {
            "id": "circle_style",
            "type": "circle",
            "source": "source_nameX",
            "paint": {
                "circle-color": "rgba(35, 132, 126, 1)",
                "circle-radius": 7,
                "circle-blur": 0.5,
                "circle-stroke-color": "rgba(1, 0, 0, 1)",
                "circle-stroke-width": 1
            },
            "layout": {
                "visibility": "visible"
            }
        }
    ]
}
```

but I don't understand how and where I can put my images.

Can yo help me? 

Thanks!

**Comment by tmmschmit** [comment]
Ok, I've make some progress, I've understand how to add a default image for my markers on the layer:
```
        ....
        const layer = this.layerService.createLayer({
          title: 'Vector Layer',
          source: dataSource as any,
          sourceOptions: {
            queryable: true,
          },
          style: {
            icon: {
              src: 'assets/icons/map-pin.svg',
            },
          },
        } as VectorLayerOptions) as VectorLayer;
        ....
```
But I haven't understood yet how to define the style for the selected markers... Currently it's display the default Circle when selected: 
![Screenshot from 2021-01-05 17-42-17](https://user-images.githubusercontent.com/60105862/103707882-7a856180-4f7d-11eb-82bf-f366f07bacde.png)

If you have some time to help me it would be great!

Thanks!

**Comment by mbarbeau** [comment]
Hello, sorry for the long delay.
The easiest way is to change the style in the selection strategy.

Here is an example:

```
const selectedStyle = this.styleService.createStyle({
    icon: {
      src: 'assets/icons/map-pin.svg', 
    }
  });

const selectionStrategy = new FeatureStoreSelectionStrategy({
  map: this.map,
  motion: FeatureMotion.Default,
  layer: new VectorLayer({
    zIndex: 300,
    source: new FeatureDataSource(),
    style: selectedStyle,
    showInLayerList: false,
    exportable: false,
    browsable: false
  })
});
```

Contact us again if you need clarification.

Have a good day !

**Comment by tmmschmit** [comment]
Thanks for your answer, I've found a way to do this with the `this.map.overlay`.  But your solution is way better!

**Comment by tmmschmit** [comment]
I'll have another question; some of my markers are overlapping (I'm planning to add clusters, I'm trying to figure out how to do with the example https://infra-geo-ouverte.github.io/igo2-lib/#/spatial-filter). I would like to be able to select only one at a time. I tried with `many: false` but it doesn't seem to be the correct property.

Thanks again!

**Comment by mbarbeau** [comment]
By selecting on the map, it has no property to select only one feature.
If you are comfortable modifying the library, you can add this functionality in the selection strategy.
Otherwise, you can observe the states of the store and deselect the other elements when it has more than one feature selected.

```
this.store.stateView.manyBy$(
    record => record.state.selected === true
  ).subscribe(selected => {
    if (selected.length > 1) {
      this.store.state.updateMany([selected[0]], { selected: true }, true);
    }
  }
);
```

**Comment by tmmschmit** [comment]
Thanks I'll go with the second solution. I'm also stuck with the clusters, I'll open another issue about this!
