### ISSUE TITLE
Display clusters instead of overlapped markers

### ISSUE THREAD

**Issue by tmmschmit** [infra-geo-ouverte/igo2-lib#798]
Hello, like I said in https://github.com/infra-geo-ouverte/igo2-lib/issues/791#issuecomment-755821527, I trying to add clustered markers exactly like https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html.

Currently my markers are in the store :
```
this.store.load(entitiesList);
```
Then I load them  on the layer via

```
  this.dataSourceService
      .createAsyncDataSource({
        type: 'vector',
      })
      .subscribe(dataSource => {
        console.log(dataSource.constructor);
        const layer = this.layerService.createLayer({
          title: 'Vector Layer',
          source: dataSource as any,
          sourceOptions: {
            queryable: true,
          },
          style: {
            icon: {
              src: 'assets/icons/map-pin.svg',
              scale: 1.5
            },
          },
        } as VectorLayerOptions) as VectorLayer;
        this.map.addLayer(layer);
        this.store.bindLayer(layer);   <-- this line 
        loadingStrategy.activate();
        selectionStrategy.activate();
      });

 ```

From what I understand in https://github.com/infra-geo-ouverte/igo2-lib/blob/master/demo/src/app/geo/spatial-filter/spatial-filter.component.ts#L296, I need to convert my Entities to Features, declare a new layer and add them to it?

Did I have to manually define which markers to remove from the vector layer and which markers to add to the layer cluster depending on the current zoom?

Thanks!

**Comment by PhilippeLafreniere18** [comment]
Hi,

We did not test it from store entities, so yes I advice you to push your entities into features array. Then you could create a new cluster datasource layer to add the point features to (similar to spatial-filter). 

I am not sure to understand the last question, but what I can tell you is that if the cluster layer has been created directly from your features, you'll only need to define the icon you want to display in the feature's attributes. The distance parameter will allow you to play with the number of clusters you want (https://openlayers.org/en/latest/examples/cluster.html). The icon (marker) will display the more you zoom in (when cluster within a certain distance have less than 2 features).

Don't hesitate if it's not clear !
Have a good one !

**Comment by mbarbeau** [comment]
Hello,
First, you must use cluster datasource
Then, as Philippe said, the loading strategy is not compatible with cluster datasource. So you need convert your Entities to Features.
It will look like this: 

```
this.dataSourceService
      .createAsyncDataSource({
        type: 'cluster',
        queryable: true,
        distance: 60
      } as ClusterDataSourceOptions)
      .subscribe(dataSource => {
        const layer = this.layerService.createLayer({
          title: 'Vector Layer',
          visible: true,
          source: dataSource,
          clusterBaseStyle: style
        }) as VectorLayer;
        
        const featuresOl = this.store.entities$.value.map(feature => {
            return featureToOl(feature as any, this.map.projection);
          });
        dataSource.ol.source.addFeatures(featuresOl);

        this.map.addLayer(layer);
        this.store.bindLayer(layer);
        // loadingStrategy.activate();
        selectionStrategy.activate();
  });
```

Also, as the store and the clusters are detached, if you want to query features on the map, you have to use the IgoQueryModule. (to include in your module.ts).
In your html:
```
<igo-map-browser [map]="map" [view]="view"
  igoQuery
  [queryFeatures]="true"
  (query)="handleQueryResults($event)"
  >
```
  
And in your component.ts:
```
handleQueryResults(e) {
    const features = e.features.map(f => this.store.get(f.properties.id));
    this.store.state.updateMany(features, {selected: true}, true);
  }
```
Have a good day !

**Comment by tmmschmit** [comment]
Thanks again to you two! Everything works well!

I'm just have (again) trouble with the styles. I trying to use `this.styleService.createClusterStyle()` for the layer and `this.styleService.createStyle` in each Feature without success. :thinking: 

Can you help me one last time? Thanks!

**Comment by mbarbeau** [comment]
What is the desired end result ?
You can change the style of a single feature with clusterBaseStyle and to change the style of the cluster, you must use clusterParam.
Unfortunately, clusters currently do not support a function in style. So, we are a little more limited in the personalization of the style.

```
clusterBaseStyle: this.styleService.createStyle({
  icon: {
    src: 'assets/icons/place_green_36px.svg',
  }
}),
clusterParam: {
  clusterRanges: [
    {
      showRange: true,
      dynamicRadius: true,
      style: {
        circle: {
          opacity: 0.4,
          radius: 7,
          stroke: {
            color: 'white',
            width: 1
          },
          fill : {
            color: 'green',
          }
        }
      }
    }
  ]
}
```

**Comment by tmmschmit** [comment]
Thanks again, with your help I was able to get what I wanted. Do you know how to change the font or put make it bold in clusters?
I tried with the `font: '12px Calibri, sans-serif'` property, but it doesn't seem to work.

**Comment by mbarbeau** [comment]
This isn't possible to do directly in the constructor but you can work around this by changing the style afterwards.

```
const baseStyle = {
  icon: {
    src: 'assets/icons/place_green_36px.svg',
  }
};

const clusterParam = {
  clusterRanges: [
    {
      dynamicRadius: true,
      style: {
        circle: {
          opacity: 0.4,
          radius: 7,
          stroke: {
            color: 'white',
            width: 1
          },
          fill : {
            color: 'green',
          }
        },
        text: {
          text: '',
          font:'12px Calibri, sans-serif'
        }
      }
    }
  ]
}

layer.ol.setStyle(feature => {
  const size = feature.get('features').length;
  clusterParam.clusterRanges[0].style.text.text = size.toString();
  return this.styleService.createClusterStyle(feature, clusterParam, baseStyle);
})
```
