### ISSUE TITLE
IgoMap.ol.forEachFeatureAtPixel does not return features that are at a specific pixel.

### ISSUE THREAD

**Issue by iamkinetic** [infra-geo-ouverte/igo2-lib#85]
I'm using the IgoMap and I have added a few features that are correctly displayed on the map.  I've add this code to handle the click event on those feature:

    this.map.ol.getViewport().addEventListener('click', (e) => {
        const eventPixel = this.map.ol.getEventPixel(e);
        this.map.ol.forEachFeatureAtPixel(eventPixel, (feature, layer) => {
            console.log('click on feature', feature); 
        });  
    });

Unfortunately, it seems like the function forEachFeatureAtPixel is not returning anything even when I'm clicking on the feature.  Can you help me with this problem?

I'm using Igo2 v0.8.1 (I can't use the latest version because our application is using Angular 4.1.3).

**Comment by iamkinetic** [comment]
I've test some more this morning and I've been able to click on one of the feature.  It feels like the "clickable zone" is only one pixel.

**Comment by iamkinetic** [comment]
So i've got one my feature at coordinate : [-7870148.936216107, 5801355.334921141].  If i get the pixel at this specific coordinate (using the chrome console):

    map.ol.getPixelAtCoordinate([-7870148.936216107, 5801355.334921141])

It returns [410.86174125852995, 227.62009292573202].  If I then call this function : 

    map.ol.hasFeatureAtCoordinate([410.86174125852995, 227.62009292573202]) 

It returns false.  That doesn't make much sense to me.

**Comment by iamkinetic** [comment]
Ok, i've just noticed something really interesting.  Once my feature are displayed on the map, I can click on them and it won't work at all.  If I resize the browser and then click on one of the feature, it works perfectly.  

Is there something specific I'm supposed to do once I'm done loading the features?  Is this a known bug in the version I'm using?

**Comment by gignacnic** [comment]
What kind of feature you are loading on the map, geojson or a WMS layer in the map window?

**Comment by iamkinetic** [comment]
Geojson.

**Comment by cbourget** [comment]
You should use the "ol.interaction.Select" since you're working with features. See the example here: https://openlayersbook.github.io/ch08-interacting-with-your-map/example-02.html

About "map.ol.hasFeatureAtCoordinate" that you mentionned in a previous post, it seems that you're passing the pixels instead of the coordinates which explains why it returns false.

**Comment by iamkinetic** [comment]
Yeah, I was using hasFeatureAtPixel and not hasFeatureAtCoordinate.  

I'm not trying to make my feature selectable like they are in that example, I'm just trying to get them to be clickable without having to resize the map first.  That's my current bug.

forEachFeatureAtPixel is never returning anything if I don't manually resize the map first.

**Comment by iamkinetic** [comment]
I've added this line `this.map.ol.updateSize();` right after I'm done adding my features and forEachFeatureAtPixel is now doing its job without having to resize the map to trigger some internal refresh stuff.

I'm not sure if this is the "right" fix, but it does the job for now.  Is it an ok fix?

**Comment by cbourget** [comment]
Yes, I think it's acceptable to leave it that way. I'm sorry I didn't get time to check onto this issue.

**Comment by matrottier** [comment]
@pelo
