### ISSUE TITLE
igo2 v 1.7.1 npm install step before compiling igo2-lib throws errors

### ISSUE THREAD

**Issue by sukeshlaghate** [infra-geo-ouverte/igo2-lib#856]
**Please tell us about your environment:**

1. **Operating system, Browser**
    * Lubuntu 20.04
    * Firefox 88.0.1 (64-bit)

2. **Igo Version:**
1.7.1 

3. **Node:**
v13.14.0

I have downloaded repo code and as first step of compilation process when I run `npm install` I am getting multiple errors.

Log file for install is attached for reference. 
[install.log](https://github.com/infra-geo-ouverte/igo2-lib/files/6471733/install.log)

I have tried deleting node_modules folder and re running npm install still getting same errors.

Would appreciate if anyone can give pointers on how to resolve this issue?

Regards,
Sukesh.

**Comment by pelord** [comment]
I will take a look soon.

**Comment by sukeshlaghate** [comment]
@pelord Thank you. 
Also observed same issue for igo2-lib 1.7.2 
Steps to reproduce issue:
1. download latest repository code
2. unzip to folder
3. run npm install : you will see deluge of errors

**Comment by pelord** [comment]
You are running on the lts nodejs version?

**Comment by pelord** [comment]
I've seen that you use 13.14. sorry.

**Comment by sukeshlaghate** [comment]
Closing since npm install issue is resolved in version 1.8.1
